import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

function Layout({ page, setPage, children }) {
  const nav = [["dashboard","Dashboard"],["courses","Courses"],["tests","Mock Tests"],["interview","AI Interview"],["coding","Coding"],["notes","My Notes"]];
  return <div className="app">
    <aside>
      <div className="brand">AI<span>Learn</span></div>
      <div className="tag">Learn • Practice • Interview</div>
      {nav.map(([id,label])=><button className={page===id?"nav active":"nav"} onClick={()=>setPage(id)} key={id}>{label}</button>)}
      <div className="side-bottom">Final Year Project<br/><small>AI Learning Platform</small></div>
    </aside>
    <main><header><div><b>{nav.find(x=>x[0]===page)?.[1] || "Dashboard"}</b><div className="muted">Personalized learning workspace</div></div><div className="avatar">SB</div></header>{children}</main>
  </div>
}

function Dashboard({setPage}) {
  return <section>
    <div className="hero"><div><div className="eyebrow">YOUR AI LEARNING COACH</div><h1>Prepare smarter.<br/><span>Interview stronger.</span></h1><p>Learn programming, practice coding, take monitored mock tests and complete AI-powered video interviews.</p><button className="primary" onClick={()=>setPage("interview")}>Start AI Interview →</button></div><div className="hero-card"><div className="orb">AI</div><b>Interview readiness</b><strong>82%</strong><div className="progress"><i style={{width:"82%"}}/></div><small>+8% this month</small></div></div>
    <div className="grid4"><Metric n="12" t="Courses enrolled"/><Metric n="38" t="Tests completed"/><Metric n="14" t="Interviews"/><Metric n="82%" t="Readiness score"/></div>
    <div className="section-title"><h2>Quick start</h2></div>
    <div className="cards"><Action icon="◉" title="Mock Test + Screen Share" text="Timed AI test with browser screen sharing." onClick={()=>setPage("tests")}/><Action icon="◌" title="AI Video Interview" text="Practice HR, technical and coding interviews." onClick={()=>setPage("interview")}/><Action icon="⌘" title="Coding Practice" text="Solve coding problems and run test cases." onClick={()=>setPage("coding")}/></div>
  </section>
}
function Metric({n,t}){return <div className="metric"><strong>{n}</strong><span>{t}</span></div>}
function Action({icon,title,text,onClick}){return <button className="action" onClick={onClick}><div className="action-icon">{icon}</div><div><b>{title}</b><p>{text}</p></div><span>→</span></button>}

function Courses(){ const [courses,setCourses]=useState([]); useEffect(()=>fetch(API+"/courses").then(r=>r.json()).then(setCourses).catch(()=>{}),[]); return <section><div className="section-title"><div><h1>Learning paths</h1><p className="muted">Build job-ready programming skills.</p></div></div><div className="course-grid">{courses.map(c=><div className="course" key={c.id}><div className="course-top">{c.language||c.title.slice(0,2)}<span>{c.level}</span></div><h2>{c.title}</h2><p>Structured lessons, practice problems, assessments and AI assistance.</p><div className="progress"><i style={{width:c.progress+"%"}}/></div><small>{c.progress}% complete</small><button className="outline">Continue learning</button></div>)}</div></section> }

function Tests(){ const [running,setRunning]=useState(false); const [sharing,setSharing]=useState(false); const [stream,setStream]=useState(null); const [question,setQuestion]=useState(1); const video=useRef(); const startShare=async()=>{try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}); setStream(s);setSharing(true); if(video.current) video.current.srcObject=s; s.getVideoTracks()[0].onended=()=>setSharing(false)}catch(e){alert("Screen sharing permission was cancelled.")}}; return <section><div className="section-title"><div><h1>AI Mock Test</h1><p className="muted">Timed assessment with optional screen sharing and webcam.</p></div>{!running&&<button className="primary" onClick={()=>setRunning(true)}>Start test</button>}</div>{!running?<div className="setup"><h2>Assessment setup</h2><label>Language<select><option>Java</option><option>Python</option><option>C++</option><option>C</option></select></label><label>Difficulty<select><option>Medium</option><option>Easy</option><option>Hard</option></select></label><div className="info">✓ 20 AI-generated questions &nbsp; ✓ 30 minute timer &nbsp; ✓ Coding questions included</div></div>:<div className="test-room"><div className="test-main"><div className="timer">29:42 remaining</div><h2>Question {question} of 20</h2><p>Which concept allows a subclass to provide a specific implementation of a method already defined in its parent class?</p>{["Encapsulation","Method overriding","Compilation","Aggregation"].map((x,i)=><button className="answer" key={x} onClick={()=>setQuestion(Math.min(20,question+1))}>{String.fromCharCode(65+i)}. {x}</button>)}<div className="test-actions"><button className="outline" onClick={()=>setRunning(false)}>Submit test</button></div></div><div className="monitor"><h3>Assessment monitor</h3><div className="screenbox">{sharing?<video ref={video} autoPlay muted/>:<div className="screen-placeholder">Screen sharing is off</div>}</div><button className={sharing?"outline":"primary"} onClick={startShare}>{sharing?"Screen sharing active":"Share screen"}</button><p className="muted">Screen sharing requires explicit browser permission.</p></div></div>}</section>}

function Interview(){ const [started,setStarted]=useState(false); const [camera,setCamera]=useState(false); const [stream,setStream]=useState(null); const video=useRef(); const start=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setStream(s);setCamera(true);setStarted(true);setTimeout(()=>{if(video.current)video.current.srcObject=s},50)}catch(e){alert("Camera/microphone permission is required for the video interview.")}}; const stop=()=>{stream?.getTracks().forEach(t=>t.stop());setCamera(false);setStarted(false)}; return <section><div className="section-title"><div><h1>AI Video Interview</h1><p className="muted">Practice a realistic, adaptive interview with an AI interviewer.</p></div>{started?<button className="danger" onClick={stop}>End interview</button>:<button className="primary" onClick={start}>Enter interview room</button>}</div>{!started?<div className="interview-grid"><div className="setup"><h2>Choose interview</h2><label>Interview type<select><option>Technical</option><option>HR</option><option>Coding</option><option>Java Developer</option><option>Python Developer</option></select></label><label>Experience<select><option>Fresher</option><option>1–3 years</option><option>3–5 years</option></select></label><div className="info">AI adapts follow-up questions based on your answers.</div></div><div className="feature-list"><b>Included in the session</b><p>🎥 Live candidate video</p><p>🎤 Voice questions and answers</p><p>🤖 AI-generated follow-ups</p><p>📊 Communication + technical scoring</p><p>📝 Transcript and improvement report</p></div></div>:<div className="video-room"><div className="ai-panel"><div className="ai-avatar">AI</div><b>AI Interviewer</b><p>“Tell me about yourself and your recent programming project.”</p><div className="listening">● Listening for your answer...</div></div><div className="candidate"><video ref={video} autoPlay muted/><div className="video-controls"><button>🎤</button><button>📷</button><button>🖥️</button><button className="danger" onClick={stop}>End</button></div></div><div className="transcript"><b>Live transcript</b><p className="muted">Your spoken response will appear here after speech-to-text is connected.</p></div></div>}</section>}

function Coding(){return <section><div className="section-title"><div><h1>Coding Interview</h1><p className="muted">Solve a problem while discussing your approach.</p></div><button className="primary">Run code ▶</button></div><div className="coding-room"><div className="problem"><b>AI Challenge</b><h2>Two Sum</h2><p>Given an array of integers and a target, return the indices of two numbers that add up to the target.</p><h3>Example</h3><code>nums = [2,7,11,15], target = 9</code><p>Expected output: <code>[0,1]</code></p></div><textarea defaultValue={"function twoSum(nums, target) {\n  // Write your solution here\n}\n"}/></div></section>}

function Notes(){const [notes,setNotes]=useState([{title:"Java OOP revision",text:"Polymorphism, inheritance, abstraction and encapsulation."}]); const [title,setTitle]=useState(""); const [text,setText]=useState(""); return <section><div className="section-title"><div><h1>My Notes</h1><p className="muted">Save revision points and interview preparation notes.</p></div></div><div className="notes"><div className="note-form"><input placeholder="Note title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Write your note..." value={text} onChange={e=>setText(e.target.value)}/><button className="primary" onClick={()=>{if(title||text){setNotes([...notes,{title,text}]);setTitle("");setText("")}}}>Save note</button></div>{notes.map((n,i)=><div className="saved-note" key={i}><h3>{n.title}</h3><p>{n.text}</p></div>)}</div></section>}

function App(){const [page,setPage]=useState("dashboard"); const pages={dashboard:<Dashboard setPage={setPage}/>,courses:<Courses/>,tests:<Tests/>,interview:<Interview/>,coding:<Coding/>,notes:<Notes/>}; return <Layout page={page} setPage={setPage}>{pages[page]}</Layout>}
createRoot(document.getElementById("root")).render(<App/>);
